version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: alpine

    steps:
      - run:
          name: "Step 1"
          command: |
            echo "Step 1 start"
            sleep 5
            echo "Step 1 finish"
      - run:
          name: "Step 2"
          command: |
            echo "Step 2"
            sleep 5
            echo "Step 2 Finish"
      - run:
          name: "Step 3"
          command: |
            echo "Step 3"
            sleep 5
            echo "Step 3 Finish"
      - run:
          name: "Step 4"
          command: |
            echo "Step 4 start"
            sleep 5
            echo "Step 4 finish"
      - run:
          name: "Step 5"
          command: |
            echo "Step 5"
            sleep 5
            echo "Step 5 Finish"
      - run:
          name: "Step 6"
          command: |
            echo "Step 6"
            sleep 5
            echo "Step 6 Finish"
      - deploy:
          name: "Deploy"
          command: |
            if :; then
              echo "Deploy start"
              bash -x ./deploy.sh 1
              echo "Deploy finish"
            fi
      - run:
          name: "Postprocess"
          command: echo "Postprocess"


