version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: ubuntu

    steps:
      - checkout
      - run:
          name: "Step 1"
          command: |
            echo "Step 1 start"
            echo "Step 1 finish"
      - deploy:
          name: "Deploy"
          command: |
            set +e
            if :; then
              echo "Deploy start"
              bash -x ./deploy.sh 1
              ret=$?
              echo "Deploy finish"

              bash -x ./postprocess.sh
              exit $ret
            fi
